import React, { useState, useEffect } from 'react'
import { useLocation, useNavigate, Link } from 'react-router-dom'
import { motion } from 'framer-motion'
import { ShieldAlert, RefreshCw, KeyRound } from 'lucide-react'
import client from '../../api/client'
import { useAuthStore } from '../../store/authStore'
import { toast } from 'sonner'

export default function Verify2FAPage() {
  const location = useLocation()
  const navigate = useNavigate()
  const { setAuth } = useAuthStore()
  
  const [code, setCode] = useState('')
  const [loading, setLoading] = useState(false)
  const [tempToken, setTempToken] = useState('')

  useEffect(() => {
    const tokenFromState = location.state?.tempToken
    if (tokenFromState) {
      setTempToken(tokenFromState)
    } else {
      toast.error('Authentication session expired. Please log in again.')
      navigate('/login')
    }
  }, [location, navigate])

  const handleSubmit = async (e) => {
    e.preventDefault()
    if (code.length !== 6 || isNaN(code)) {
      toast.error('Please enter a valid 6-digit code')
      return
    }

    setLoading(true)
    try {
      const res = await client.post('/auth/verify-2fa', {
        tempToken,
        code
      })
      if (res.data?.success) {
        const data = res.data
        const token = data.accessToken || data.token
        localStorage.setItem('token', token)
        setAuth(data.user, token)
        toast.success(`Welcome back, ${data.user.username || data.user.email}!`)
        if (data.user.activeRole === 'admin') {
          navigate('/admin')
        } else {
          navigate('/dashboard')
        }
      }
    } catch (err) {
      toast.error(err.response?.data?.message || 'Invalid 2FA verification code')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div style={{ minHeight: '80vh', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '0 24px', background: '#0a0a0a' }}>
      <motion.div
        initial={{ opacity: 0, scale: 0.95 }}
        animate={{ opacity: 1, scale: 1 }}
        transition={{ duration: 0.4 }}
        className="card"
        style={{
          width: '100%',
          maxWidth: 420,
          background: '#111111',
          border: '1px solid rgba(255, 255, 255, 0.05)',
          borderRadius: 16,
          padding: 36,
          textAlign: 'center',
          display: 'flex',
          flexDirection: 'column',
          gap: 20
        }}
      >
        <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
          <KeyRound size={64} style={{ color: '#f5c518', margin: '0 auto' }} />
          <h2 style={{ fontSize: 22, fontWeight: 800, color: '#ffffff', margin: 0 }}>2-Step Verification</h2>
          <p style={{ color: '#a0a0a0', fontSize: 14, margin: 0, lineHeight: 1.6 }}>
            Enter the 6-digit code generated by your authenticator app to log in.
          </p>
        </div>

        <form onSubmit={handleSubmit} style={{ display: 'flex', flexDirection: 'column', gap: 16, textAlign: 'left', marginTop: 8 }}>
          <div className="form-group">
            <label className="form-label" style={{ fontSize: 11, fontWeight: 600, color: '#a0a0a0' }}>
              Authenticator Code
            </label>
            <input
              type="text"
              maxLength={6}
              value={code}
              onChange={(e) => setCode(e.target.value.replace(/\D/g, ''))}
              placeholder="e.g. 123456"
              className="form-input"
              style={{
                background: '#0a0a0a',
                border: '1px solid #222222',
                borderRadius: 8,
                padding: '12px 14px',
                color: '#ffffff',
                textAlign: 'center',
                letterSpacing: '0.25em',
                fontSize: 18,
                fontFamily: 'monospace'
              }}
              autoFocus
            />
          </div>

          <button
            type="submit"
            disabled={loading || code.length !== 6}
            className="btn btn-primary"
            style={{
              width: '100%',
              padding: '12px 24px',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              gap: 8,
              fontWeight: 700,
              fontSize: 14,
              borderRadius: 8
            }}
          >
            {loading ? (
              <RefreshCw size={16} style={{ animation: 'spin 1.5s linear infinite' }} />
            ) : (
              <ShieldAlert size={16} />
            )}
            Verify & Log In
          </button>
        </form>

        <div style={{ fontSize: 14, color: '#666666', marginTop: 8 }}>
          Having trouble? <Link to="/login" style={{ color: '#f5c518', fontWeight: 600 }} onMouseEnter={e => e.currentTarget.style.textDecoration = 'underline'} onMouseLeave={e => e.currentTarget.style.textDecoration = 'none'}>Back to login</Link>
        </div>
      </motion.div>
      <style>{`
        @keyframes spin {
          to { transform: rotate(360deg); }
        }
      `}</style>
    </div>
  )
}
